# Generated by Django 4.2.3 on 2023-07-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название олимпиады')),
                ('degree', models.SmallIntegerField(verbose_name='Рекомендуемый класс обучения')),
                ('date_of_start', models.DateTimeField(verbose_name='Начало проведения олимпиады')),
                ('registration_dedline', models.DateTimeField(verbose_name='Дата окончания регистрации')),
                ('olympiad_duration', models.DurationField(verbose_name='Продолжительность олимпиады')),
            ],
            options={
                'verbose_name': 'Олимпиада',
                'verbose_name_plural': 'Олимпиады',
                'ordering': ['subject', 'degree', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.SmallIntegerField(verbose_name='Номер раздела олимпиады')),
                ('points', models.SmallIntegerField(verbose_name='Количество баллов')),
            ],
            options={
                'verbose_name': 'Раздел олимпиады',
                'verbose_name_plural': 'Разделы олимпиады',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Школьный предмет',
                'verbose_name_plural': 'Школьные предметы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField(verbose_name='Формулировка вопроса')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiad', verbose_name='Олимпиада')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='olympiads.questionsection', verbose_name='Раздел олимпиады')),
            ],
            options={
                'verbose_name': 'Вопрос олимпиады',
                'verbose_name_plural': 'Вопросы олимпиады',
                'ordering': ['olympiad', 'section'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(verbose_name='Дата регистрации')),
                ('answers', models.JSONField(verbose_name='Ответы ученика')),
                ('score', models.IntegerField(verbose_name='Количество баллов')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiad', verbose_name='Название олимпиады')),
            ],
            options={
                'verbose_name': 'Регистрация участника олимпиады',
                'verbose_name_plural': 'Регистрация участника олимпиады',
                'ordering': ['olympiad', 'score', 'user'],
            },
        ),
    ]
