# Generated by Django 4.2.3 on 2023-07-14 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiaduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя участника'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='participants',
            field=models.ManyToManyField(through='olympiads.OlympiadUser', to=settings.AUTH_USER_MODEL, verbose_name='Участники олимпиады'),
        ),
        migrations.AddField(
            model_name='olympiad',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.subject', verbose_name='Название дисциплины'),
        ),
    ]
