# Generated by Django 4.2.3 on 2023-07-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiaduser',
            name='answers',
            field=models.JSONField(null=True, verbose_name='Ответы ученика'),
        ),
        migrations.AlterField(
            model_name='olympiaduser',
            name='registration_date',
            field=models.DateTimeField(null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='olympiaduser',
            name='score',
            field=models.IntegerField(null=True, verbose_name='Количество баллов'),
        ),
    ]
