# Generated by Django 4.2.3 on 2023-07-17 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiads', '0003_alter_olympiaduser_answers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiaduser',
            options={'ordering': ['olympiad', 'user'], 'verbose_name': 'Регистрация участника олимпиады', 'verbose_name_plural': 'Регистрация участника олимпиады'},
        ),
        migrations.RemoveField(
            model_name='olympiaduser',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='olympiaduser',
            name='score',
        ),
        migrations.CreateModel(
            name='UsersAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ участника')),
                ('score', models.SmallIntegerField(verbose_name='Количество баллов за ответ')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='olympiads.question', verbose_name='Вопрос олимпиады')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник олимпиады')),
            ],
            options={
                'verbose_name': 'Решение олимпиады',
                'verbose_name_plural': 'Решения олимпиад',
                'ordering': ['user'],
            },
        ),
    ]
