# Generated by Django 4.2.3 on 2023-07-17 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiads', '0004_alter_olympiaduser_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersAnswers',
            new_name='UserAnswer',
        ),
    ]
