# Generated by Django 4.2.3 on 2023-08-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0005_rename_usersanswers_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Путь до изображения'),
        ),
    ]
