# Generated by Django 4.2.3 on 2023-08-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0006_olympiad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='image',
            field=models.CharField(blank=True, null=True, verbose_name='Путь до изображения от static директории'),
        ),
    ]
