# Generated by Django 4.2.3 on 2023-09-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0008_olympiad_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='possible_answers',
            field=models.TextField(blank=True, null=True, verbose_name='Варианты ответов, перечисленные через ","'),
        ),
    ]
