# Generated by Django 4.2.3 on 2023-09-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0009_question_possible_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='olympiaduser',
            options={'ordering': ['olympiad', 'user'], 'verbose_name': 'Данные о прохождении участником олимпиады', 'verbose_name_plural': 'Данные о прохождениях участниками олимпиад'},
        ),
        migrations.AddField(
            model_name='olympiaduser',
            name='earned_mark',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество набранных баллов'),
        ),
        migrations.AddField(
            model_name='olympiaduser',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Участник отправил ответы олимпиады на проверку?'),
        ),
        migrations.AddField(
            model_name='olympiaduser',
            name='ranking_place',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Место участника в рейтинге'),
        ),
        migrations.AddField(
            model_name='olympiaduser',
            name='total_mark',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Максимально возможное количество баллов'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionSection',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
