# Generated by Django 4.2.3 on 2023-10-17 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiads', '0010_remove_useranswer_question_remove_useranswer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField(verbose_name='Формулировка вопроса')),
                ('possible_answers', models.TextField(blank=True, null=True, verbose_name='Варианты ответов, перечисленные через ","')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.olympiad', verbose_name='Олимпиада')),
            ],
            options={
                'verbose_name': 'Вопрос олимпиады',
                'verbose_name_plural': 'Вопросы олимпиады',
                'ordering': ['olympiad', 'section'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.SmallIntegerField(verbose_name='Номер раздела олимпиады')),
                ('points', models.SmallIntegerField(verbose_name='Количество баллов')),
            ],
            options={
                'verbose_name': 'Раздел олимпиады',
                'verbose_name_plural': 'Разделы олимпиады',
                'ordering': ['section'],
            },
        ),
        migrations.AlterModelOptions(
            name='olympiaduser',
            options={'ordering': ['olympiad', 'user'], 'verbose_name': 'Регистрация участника олимпиады', 'verbose_name_plural': 'Регистрация участника олимпиады'},
        ),
        migrations.RemoveField(
            model_name='olympiaduser',
            name='earned_mark',
        ),
        migrations.RemoveField(
            model_name='olympiaduser',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='olympiaduser',
            name='ranking_place',
        ),
        migrations.RemoveField(
            model_name='olympiaduser',
            name='total_mark',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ участника')),
                ('score', models.SmallIntegerField(verbose_name='Количество баллов за ответ')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='olympiads.question', verbose_name='Вопрос олимпиады')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник олимпиады')),
            ],
            options={
                'verbose_name': 'Решение олимпиады',
                'verbose_name_plural': 'Решения олимпиад',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='olympiads.questionsection', verbose_name='Раздел олимпиады'),
        ),
    ]
