# Generated by Django 4.1.3 on 2023-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0012_alter_olympiaduser_options_olympiaduser_earned_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь до изображения от static директории'),
        ),
    ]
