# Generated by Django 4.2.13 on 2024-06-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0013_alter_olympiad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionSection',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
