# Generated by Django 4.2.13 on 2024-06-26 18:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiads', '0014_remove_useranswer_question_remove_useranswer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер вопроса')),
                ('title', models.CharField(max_length=50, verbose_name='Название вопроса')),
                ('description', models.CharField(max_length=200, verbose_name='Формулировка вопроса')),
                ('a', models.CharField(max_length=255, null=True)),
                ('a_is_correct', models.BooleanField(default=False)),
                ('b', models.CharField(max_length=255, null=True)),
                ('b_is_correct', models.BooleanField(default=False)),
                ('c', models.CharField(blank=True, max_length=255, null=True)),
                ('c_is_correct', models.BooleanField(default=False)),
                ('d', models.CharField(blank=True, max_length=255, null=True)),
                ('d_is_correct', models.BooleanField(default=False)),
                ('e', models.CharField(blank=True, max_length=255, null=True)),
                ('e_is_correct', models.BooleanField(default=False)),
                ('f', models.CharField(blank=True, max_length=255, null=True)),
                ('f_is_correct', models.BooleanField(default=False)),
                ('mark', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Баллы за вопрос')),
                ('olympiad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiads.olympiad', verbose_name='Вопрос для какой олимпиады')),
            ],
            options={
                'verbose_name': 'Вопрос с множественным ответом',
                'verbose_name_plural': 'Вопросы с множественным ответом',
            },
        ),
        migrations.CreateModel(
            name='OneChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер вопроса')),
                ('title', models.CharField(max_length=50, verbose_name='Название вопроса')),
                ('description', models.CharField(max_length=200, verbose_name='Формулировка вопроса')),
                ('a', models.CharField(max_length=255, null=True)),
                ('a_is_correct', models.BooleanField(default=False)),
                ('b', models.CharField(max_length=255, null=True)),
                ('b_is_correct', models.BooleanField(default=False)),
                ('c', models.CharField(blank=True, max_length=255, null=True)),
                ('c_is_correct', models.BooleanField(default=False)),
                ('d', models.CharField(blank=True, max_length=255, null=True)),
                ('d_is_correct', models.BooleanField(default=False)),
                ('mark', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Баллы за вопрос')),
                ('olympiad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiads.olympiad', verbose_name='Вопрос для какой олимпиады')),
            ],
            options={
                'verbose_name': 'Вопрос с одним ответом',
                'verbose_name_plural': 'Вопросы с одним ответом',
            },
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер вопроса')),
                ('title', models.CharField(max_length=50, verbose_name='Название вопроса')),
                ('description', models.CharField(max_length=150, verbose_name='Формулировка вопроса')),
                ('first_statement', models.CharField(max_length=150, null=True, verbose_name='Первое утверждение')),
                ('second_statement', models.CharField(max_length=150, null=True, verbose_name='Второе утверждение')),
                ('answer', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=3, verbose_name='номер верного утверждения')),
                ('marks', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество баллов за правильный ответ')),
                ('olympiad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiads.olympiad', verbose_name='Вопрос для какой олимпиады')),
            ],
            options={
                'verbose_name': 'Вопрос "Какое из утверждений верно"',
                'verbose_name_plural': 'Вопросы "Какое из утверждений верно"',
            },
        ),
        migrations.CreateModel(
            name='TrueFalseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False, verbose_name='Ответ студента в форме True/False')),
                ('students_mark', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баллы студента за ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.truefalsequestion', verbose_name='Вопрос')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос "Какое из утверждений верно',
                'verbose_name_plural': 'Ответы на вопросы "Какое из утверждений верно',
            },
        ),
        migrations.CreateModel(
            name='OneChoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.BooleanField(default=False)),
                ('b', models.BooleanField(default=False)),
                ('c', models.BooleanField(default=False)),
                ('d', models.BooleanField(default=False)),
                ('students_mark', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баллы студента за ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.onechoicequestion', verbose_name='Вопрос')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос с одним ответом',
                'verbose_name_plural': 'Ответы на вопрос с одним ответом',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.BooleanField(default=False)),
                ('b', models.BooleanField(default=False)),
                ('c', models.BooleanField(default=False)),
                ('d', models.BooleanField(default=False)),
                ('e', models.BooleanField(default=False)),
                ('f', models.BooleanField(default=False)),
                ('students_mark', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баллы студента за ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiads.multiplechoicequestion', verbose_name='Вопрос')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос с множественным ответом',
                'verbose_name_plural': 'Ответы на вопрос с множественным ответом',
            },
        ),
    ]
