# Generated by Django 4.2.13 on 2024-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0015_multiplechoicequestion_onechoicequestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truefalsesubmission',
            name='answer',
            field=models.CharField(max_length=3, null=True, verbose_name='Ответ студента (1 или 2)'),
        ),
    ]
