# Generated by Django 4.2.13 on 2024-07-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0016_alter_truefalsesubmission_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='слаг'),
        ),
    ]
