# Generated by Django 4.2.13 on 2024-07-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0017_olympiad_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='slug',
        ),
    ]
