# Generated by Django 4.2.13 on 2024-07-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0018_remove_olympiad_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiaduser',
            name='total_mark',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='total_mark',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Максимально возможное количество баллов'),
        ),
    ]
