# Generated by Django 4.2.13 on 2024-07-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0019_remove_olympiaduser_total_mark_olympiad_total_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truefalsequestion',
            old_name='marks',
            new_name='mark',
        ),
    ]
