# Generated by Django 4.2.13 on 2024-08-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0021_alter_olympiad_total_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/olympiads', verbose_name='Изображение'),
        ),
    ]
