# Generated by Django 4.2.13 on 2024-08-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0024_remove_olympiad_description_alter_olympiad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание олимпиады'),
        ),
    ]
