# Generated by Django 4.2.15 on 2024-09-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0025_olympiad_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='olympiad_duration',
        ),
    ]
