# Generated by Django 4.2.15 on 2024-09-20 18:27

from django.db import migrations


def create_pg_trgm_extension(apps, schema_editor):
    schema_editor.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0026_remove_olympiad_olympiad_duration'),
    ]

    operations = [
        migrations.RunPython(create_pg_trgm_extension),
    ]
