# Generated by Django 4.2.15 on 2025-02-18 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0027_auto_20240920_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiads.olympiad', verbose_name='Олимпиада'),
        ),
        migrations.AlterField(
            model_name='onechoicequestion',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiads.olympiad', verbose_name='Олимпиада'),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Формулировка вопроса'),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='mark',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Баллы за вопрос'),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiads.olympiad', verbose_name='Олимпиада'),
        ),
    ]
