= Хроматин

Как известно, структурной основой хранения и передачи генетической информации является ДНК – двойная спираль, состоящая из полинуклеотидных цепей, соединенных водородными связями между азотистыми основаниями. Так как ДНК представляет собой отрицательно заряженный полимер длиной около двух метров, самостоятельная упаковка макромолекулы в ядро невозможна вследствие возникновения электростатического отталкивания между соседними участками цепей.

Компактная упаковка ДНК достигается за счет её «наматывания» на октамеры положительно заряженных гистонов, что приводит к образованию структуры «бусины на нити», где роль бусин играют комплексы гистоновых октамеров и ДНК, которые называют нуклеосомами. Изначально при изучении структурной организации хроматина в ядре было принято придерживаться иерархической модели, которая предполагает, что для уплотнения хроматина митотических хромосом ДНК-нуклеосомная цепь диаметром 11 нм складывается в 30-нм волокна, которые затем последовательно уплотняются в 120-нм хромонему, 300-нм хроматиду и 700-нм митотическую хромосому.

Однако, согласно современным представлениям, хромосомы состоят из неравномерно и неупорядоченно свернутых цепочек нуклеосом диаметром 11 нм, напоминающих структуру расплавленного полимера. Структурная и функциональная организация хромосом поддерживаются специальными мультисубъединичными белковыми комплексами – конденсинами, которые концентрируются на хроматидных осях и, связываясь со специфическими участками хроматина, предположительно, удерживают 11-нм волокна вокруг центра хромосомы.

Основываясь на разнице в организации хроматина в различных участках генома, связанную со степенью обогащения определенными посттрансляционными модификациями и взаимодействием с регуляторными белками, хроматин можно разделить на три вида доменов. Выделяют плотно упакованный гетерохроматин, маркированный гетерохроматиновым белком 1 (HP1) и метилированием лизина в 9 положении гистона Н3 (Н3К9me), менее плотно упакованный транскрипционно активный эухроматин и Polycomb-репрессированный хроматин, маркированный белками Polycomb Group (PcG) и метилированием лизина в положении 27 гистона Н3 (Н3К27me). Polycomb-репрессированные домены имеют самую плотную упаковку генома и пространственно исключают смешение с соседними активными доменами эухроматина, что предотвращает случайную активацию онтогенетических факторов транскрипции. Транскрипционно активный эухроматин менее плотно упакован и может принимать различные пространственные структуры. В нём наблюдаются сегменты со стопками нуклеосом, цепи хроматина со спиральными завитками, взаимодействие цепей, образующих петли разных размеров и множество других конформаций, на образование которых влияют посттрансляционные метки, варианты коровых гистонов, взаимодействующие с ДНК белки и длина линкерной ДНК (варьирует от 20 п. н до 75 п. н). Такой хроматиновый полиморфизм согласуется с биологическими функциями хроматина.

Таким образом, нерегулярная структура хроматина, необходимая для правильного протекания всех клеточных процессов, связанных с ДНК, обуславливается вариациями состава и стабильности нуклеосом – элементарных структурных и функциональных единиц хроматина.