# Generated by Django 4.2.3 on 2023-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='month_amount',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='course',
            name='times_a_week',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Раз в неделю'),
        ),
    ]
