# Generated by Django 4.2.3 on 2023-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Категория учащихся'),
        ),
    ]
