# Generated by Django 4.2.3 on 2023-09-11 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(related_name='course_participants', through='courses.CourseUser', to=settings.AUTH_USER_MODEL, verbose_name='Ученики курса'),
        ),
    ]
