# Generated by Django 4.2.3 on 2023-09-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_assignment_multiplechoicequestion_onechoicequestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truefalsequestion',
            options={'verbose_name': 'Вопрос "Какое из утверждений верно"', 'verbose_name_plural': 'Вопросы "Какое из утверждений верно"'},
        ),
    ]
