# Generated by Django 4.2.3 on 2023-09-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_truefalsequestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onechoicequestion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.assignment', verbose_name='Вопрос для какого задания'),
        ),
    ]
