# Generated by Django 4.2.3 on 2023-09-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0010_remove_useranswer_question_remove_useranswer_user_and_more'),
        ('courses', '0011_alter_onechoicequestion_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.assignment', verbose_name='Вопрос для какого задания'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiads.olympiad', verbose_name='Вопрос для какой олимпиады'),
        ),
        migrations.AlterField(
            model_name='onechoicequestion',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiads.olympiad', verbose_name='Вопрос для какой олимпиады'),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.assignment', verbose_name='Вопрос для какого задания'),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiads.olympiad', verbose_name='Вопрос для какой олимпиады'),
        ),
    ]
