# Generated by Django 4.2.3 on 2023-10-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='student',
        ),
    ]
