# Generated by Django 4.2.3 on 2023-10-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_comment_course_alter_comment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата публикации комментария'),
        ),
    ]
