# Generated by Django 4.2.3 on 2023-10-18 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='earned_mark',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество полученных баллов за задание'),
        ),
    ]
