# Generated by Django 4.2.3 on 2023-10-20 03:50

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_assignmentsubmission_earned_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.courses.models.upload_homework, verbose_name='Файл с решением'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(verbose_name='Описание задания'),
        ),
    ]
