# Generated by Django 4.2.3 on 2023-10-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_assignmentsubmission_homework_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(blank=True, choices=[('s', 'Ждет проверку'), ('r', 'Получено ревью задания'), ('f', 'Выполнено')], max_length=1, null=True, verbose_name='Статус выполнения задания'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Задание засчитано?'),
        ),
    ]
