# Generated by Django 4.2.3 on 2023-10-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_assignmentsubmission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя'),
        ),
    ]
