# Generated by Django 4.2.3 on 2023-10-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_assignmentsubmission_teacher_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='earned_mark',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество набранных баллов'),
        ),
    ]
