# Generated by Django 4.2.3 on 2023-10-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_courseuser_earned_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='total_mark',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Максимально возможное количество баллов'),
        ),
    ]
