# Generated by Django 4.2.3 on 2023-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_courseuser_total_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(blank=True, choices=[('-', 'Студент не начал работу'), ('s', 'Ждет проверку'), ('r', 'Получено ревью задания'), ('f', 'Выполнено')], max_length=1, null=True, verbose_name='Статус выполнения задания'),
        ),
    ]
