# Generated by Django 4.2.3 on 2024-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_alter_assignment_image_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truefalsequestion',
            name='answer',
            field=models.BooleanField(default=False, verbose_name='Ответ: True - если верно утверждение в true_choice,                                               false - если в false_choice'),
        ),
    ]
