# Generated by Django 4.2.13 on 2024-06-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_truefalsequestion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicesubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='multiplechoicesubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='onechoicequestion',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='onechoicequestion',
            name='olympiad',
        ),
        migrations.RemoveField(
            model_name='onechoicesubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='onechoicesubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='olympiad',
        ),
        migrations.RemoveField(
            model_name='truefalsesubmission',
            name='question',
        ),
        migrations.RemoveField(
            model_name='truefalsesubmission',
            name='student',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceSubmission',
        ),
        migrations.DeleteModel(
            name='OneChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='OneChoiceSubmission',
        ),
        migrations.DeleteModel(
            name='TrueFalseQuestion',
        ),
        migrations.DeleteModel(
            name='TrueFalseSubmission',
        ),
    ]
