# Generated by Django 4.2.13 on 2024-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_remove_multiplechoicesubmission_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание урока'),
        ),
        migrations.AlterField(
            model_name='course',
            name='month_amount',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Продолжительность курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='times_a_week',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Количество уроков в неделю'),
        ),
    ]
