# Generated by Django 4.2.13 on 2024-07-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_lesson_content_alter_course_month_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_mark',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Максимально возможное количество баллов'),
        ),
    ]
