# Generated by Django 4.2.13 on 2024-07-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_course_total_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseuser',
            name='total_mark',
        ),
        migrations.AlterField(
            model_name='course',
            name='total_mark',
            field=models.IntegerField(default=0, verbose_name='Максимально возможное количество баллов'),
        ),
    ]
