# Generated by Django 4.2.13 on 2024-07-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_remove_courseuser_total_mark_alter_course_total_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseuser',
            name='percent_mark',
        ),
    ]
