# Generated by Django 4.2.13 on 2024-08-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_remove_courseuser_percent_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='image',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/courses', verbose_name='Изображение'),
        ),
    ]
