# Generated by Django 4.2.13 on 2024-08-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_remove_assignment_image_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь до изображения от static директории'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/courses/', verbose_name='Изображение'),
        ),
    ]
