# Generated by Django 4.2.3 on 2023-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.SmallIntegerField(null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree_id',
            field=models.CharField(choices=[('a', 'A'), ('b', 'Б'), ('v', 'В')], default='a', max_length=1, null=True, verbose_name='Буква класса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('t', 'Учитель'), ('s', 'Ученик')], max_length=1, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
