# Generated by Django 4.2.3 on 2023-07-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_user_patronymic_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree_id',
            field=models.CharField(choices=[('a', 'A'), ('b', 'Б'), ('v', 'В')], max_length=1, null=True, verbose_name='Буква класса'),
        ),
    ]
