# Generated by Django 4.2.3 on 2023-07-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_user_degree_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree_id',
            field=models.CharField(choices=[('-', '-'), ('a', 'A'), ('b', 'Б'), ('v', 'В')], max_length=1, null=True, verbose_name='Буква класса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('-', '-'), ('t', 'Учитель'), ('s', 'Ученик')], max_length=1, null=True, verbose_name='Должность'),
        ),
    ]
