# Generated by Django 4.1.3 on 2023-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_user_degree_id_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree_id',
            field=models.CharField(choices=[('a', 'A'), ('b', 'Б'), ('v', 'В')], max_length=1, null=True, verbose_name='Буква класса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('t', 'Учитель'), ('s', 'Ученик')], max_length=1, null=True, verbose_name='Должность'),
        ),
    ]
