# Generated by Django 4.2.3 on 2023-09-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_user_degree_id_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('s', 'Ученик'), ('t', 'Учитель')], max_length=1, null=True, verbose_name='Должность'),
        ),
    ]
