# Generated by Django 4.2.3 on 2023-09-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, null=True, verbose_name='Путь до изображения от static директории'),
        ),
    ]
