# Generated by Django 4.1.3 on 2023-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Путь до изображения от static директории'),
        ),
    ]
