# Generated by Django 4.2.13 on 2024-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree_id',
            field=models.CharField(choices=[(None, 'Выберите букву Вашего класса'), ('a', 'A'), ('b', 'Б'), ('v', 'В')], max_length=1, null=True, verbose_name='Буква класса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[(None, 'Вы ученик или учитель?'), ('s', 'Ученик'), ('t', 'Учитель')], max_length=1, null=True, verbose_name='Должность'),
        ),
    ]
