# Generated by Django 4.2.15 on 2024-09-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_user_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
