# Generated by Django 4.2.15 on 2025-02-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
