
MULTIPLECHOICE_QUESTION_TYPE = 1
ONECHOICE_QUESTION_TYPE = 2
TRUEFALSE_QUESTION_TYPE = 3
RESPONSE_QUESTION_TYPE = 4
QUESTION_TYPES = [
    MULTIPLECHOICE_QUESTION_TYPE,
    ONECHOICE_QUESTION_TYPE,
    TRUEFALSE_QUESTION_TYPE,
    RESPONSE_QUESTION_TYPE,
]
